<a href="https://colab.research.google.com/github/adezxc/VU-Bioinformatics/blob/master/semester4/LinAlg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

Numpy modulis palaiko daugiamačius masysvus („matricas“). Matricos šiandieniniame moksle yra vienas iš pagrindinių darbinių arkliukų.  Numpy aplinkoje matricas galima sukurti įvairiais būdais. Vienas dažniausių būdų: panadouti np.array(...)  konstruktorių su sąrašiniu parametru. Po to, jeigu reikia, galima pritaikyti reshape() metodą, kuris duos mums tinkamų išmatavimų matricą (vektorių).  

In [ ]:
m1 = np.array([1,2,4,5])
print(type(m1))
print(m1.shape)
print(m1)
m1=m1.reshape(2,2)
print(m1)

<class 'numpy.ndarray'>
(4,)
[1 2 4 5]
[[1 2]
 [4 5]]


**Pratimas paskaitos metu. Sukurkite sąrašą iš 9 elementų,o po to - matricą $3 \times 3$.**

> Blokas su įtrauka



In [ ]:
arr = np.arange(9)
print(arr)
arr = arr.reshape(3,3)
print(arr)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Kai turime  masyvą, galime jį panaudoti atliekant veiksmus su **skaliarais**:

In [ ]:
a=np.array([1,2,3,4])
a=a.reshape(2,2)
print(2*a)
print(2+a)

[[2 4]
 [6 8]]
[[3 4]
 [5 6]]


Masyvus galima sudėti:

In [ ]:
b=np.array([10,20,30,4.0])
b=b.reshape(2,2)
c=a+b
print(c)

[[11. 22.]
 [33.  8.]]


Masyvus galima sudauginti:

In [ ]:
mas1=np.array([x*0.1 for x in range(9)])
mas2=np.linspace(1,2,9)
mas1=mas1.reshape(3,3)
mas2=mas2.reshape(3,3)
print(mas1)
print(mas2)
mas3 = mas1 @ mas2
print(mas3)
##########################
v2=np.array([1,1,2])
v2=v2.reshape(3,1)
print(mas2 @ v2)

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]
[[1.    1.125 1.25 ]
 [1.375 1.5   1.625]
 [1.75  1.875 2.   ]]
[[0.4875 0.525  0.5625]
 [1.725  1.875  2.025 ]
 [2.9625 3.225  3.4875]]
[[4.625]
 [6.125]
 [7.625]]


**Kronekerio dviеjų matricų sandauga**
Žr. pvz.: https://en.wikipedia.org/wiki/Kronecker_product#Examples
Nadojame kron(...) funkciją:

In [ ]:
mas3=np.array([x for x in range(4)])
mas4=np.linspace(1,2,9)
mas3=mas3.reshape(2,2)
mas4=mas2.reshape(3,3)
print(mas3)
print(mas4)
mas5 = np.kron(mas1,mas2)
print(mas5)

[[0 1]
 [2 3]]
[[1.    1.125 1.25 ]
 [1.375 1.5   1.625]
 [1.75  1.875 2.   ]]
[[0.     0.     0.     0.1    0.1125 0.125  0.2    0.225  0.25  ]
 [0.     0.     0.     0.1375 0.15   0.1625 0.275  0.3    0.325 ]
 [0.     0.     0.     0.175  0.1875 0.2    0.35   0.375  0.4   ]
 [0.3    0.3375 0.375  0.4    0.45   0.5    0.5    0.5625 0.625 ]
 [0.4125 0.45   0.4875 0.55   0.6    0.65   0.6875 0.75   0.8125]
 [0.525  0.5625 0.6    0.7    0.75   0.8    0.875  0.9375 1.    ]
 [0.6    0.675  0.75   0.7    0.7875 0.875  0.8    0.9    1.    ]
 [0.825  0.9    0.975  0.9625 1.05   1.1375 1.1    1.2    1.3   ]
 [1.05   1.125  1.2    1.225  1.3125 1.4    1.4    1.5    1.6   ]]


**Numpy linalg submodulis**

Čia daug labai naudingų skaičiavimo moksle funkcijų iš tiesinės algebros.
Pradžiai -- matricos laipsnis.

In [ ]:
mas6=np.array([1,2,0,3 ])
mas6=mas6.reshape(2,2)
for i in range(0,4):
   print(np.linalg.matrix_power(mas6, i))
# exp(A) <- I + A + A**2/2 + ...
# exp(x) <- 1 + x + x**2/2 + x**3/3! + x**4/4! + o(x**4)
# sin(x) <-

[[1 0]
 [0 1]]
[[1 2]
 [0 3]]
[[1 8]
 [0 9]]
[[ 1 26]
 [ 0 27]]


**Determinantas**

Naudojame *linalg.det()*:


In [ ]:
mas7=np.array([1,2,0,3,4,0,5,6,7 ])
mas7=mas7.reshape(3,3)
print(mas7)
print(np.linalg.det(mas7))

[[1 2 0]
 [3 4 0]
 [5 6 7]]
-14.000000000000004


**Matricos ar vektoriaus norma**

Naudojame *linalg.norm()*:

In [ ]:
v3=np.array([1,2,1,3])
print(np.linalg.norm(v3))
#Tai vadinamoji L2 norma:
print(np.sqrt(sum(v3*v3)))
mas8=np.array([1,2,3,4,5,6])
mas8=mas8.reshape(2,3)
print(np.linalg.norm(mas8))

3.872983346207417
3.872983346207417
9.539392014169456


**Tiesinių lygčių sistemų sprendimas**

Eina kalba apie sistemą $Ax=b$, kur $A$ - neišsigimusi ($\det A \neq 0$), o $b$ turi tūrėti tiek pat eilučių kiek turi A. Paprastai mes pripratę prie situacijos, kai $b$ - stulpelis vektorius:



In [ ]:
masA=np.array([0,2,3,4,5,6,7,8,9])
masA=masA.reshape(3,3)
vecb=np.array([6,15,24])
vecb=vecb.reshape(3,1)
x=np.linalg.solve(masA, vecb)
print(x)
###########################


[[0.]
 [3.]
 [0.]]


In [ ]:
arr = np.array([[2,3,1],[1,-1,1],[1,2,3]])
b = np.array([6,1,6])
y = np.linalg.solve(arr, b)
print(y)

[1. 1. 1.]


In [ ]:
E = np.array([[1,0,0], [0,1,0], [0,0,1]])
y = np.linalg.solve(arr, E)
print(y)
print(y @ arr)

[[ 0.38461538  0.53846154 -0.30769231]
 [ 0.15384615 -0.38461538  0.07692308]
 [-0.23076923  0.07692308  0.38461538]]
[[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [5.55111512e-17 0.00000000e+00 1.00000000e+00]]


**Pratimas paskaitos metu**

Tegul vietoje $b$ bus vienetinė matrica $E$. Kas bus $x$, jeigu spręsime sistemą $Ax=E$ ?  

In [ ]:
masB=np.eye(3)
print(masB)
####### Jūsų kodas čia #####
x1 = np.linalg.solve(masA, masB)
print(x1)
test = x1 @ masA
print(test)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-1.          2.         -1.        ]
 [ 2.         -7.          4.        ]
 [-1.          4.66666667 -2.66666667]]
[[ 1.00000000e+00 -8.88178420e-16 -2.10942375e-15]
 [-1.33226763e-15  1.00000000e+00  1.33226763e-15]
 [ 8.88178420e-16  0.00000000e+00  1.00000000e+00]]


**Atvirkštinė matrica**

Tam naudojame *np.linalg.inv()*

**Pseudoatvirkštinė**

Plačiau žiūrėkite: https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_inverse

Jeigu matrica $A$ yra $m \times n$ matrica, tai jos pseudoatvirkštinė $A^{+}$ yra  $n \times m$ matrica, kuri tenkina keturias sąlygas:

*   $A^{+}AA^{+}=A$
*   $AA^{+}A=A^{+}$
*   $(AA^{+})^{T}=AA^{+}$
*   $(A^{+}A)^{T}=A^{+}A$

**Pratimas paskaitos metu**

Sukurkite $3\times4$ matricą apskaičiuokite jos pseudoatvirkštinę (*np.linalg.pinv()*), patikrinkite nurodytas savybes.

In [ ]:
from numpy.core.fromnumeric import transpose
mat4 = np.array(range(12))
mat4new = mat4.reshape(3, 4)

mat4inv = np.linalg.pinv(mat4new)
print(mat4inv)
arr = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
parr = np.linalg.pinv(arr)

print( np.transpose(parr @ arr) - ( parr @ arr))


[[-0.3375     -0.1         0.1375    ]
 [-0.13333333 -0.03333333  0.06666667]
 [ 0.07083333  0.03333333 -0.00416667]
 [ 0.275       0.1        -0.075     ]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Lab. darbas 1, 1 dalis**

Jūsų tikslas šiame pratime -- euristiškai patirinėti tam tikros matricų klasės normų ryšius su joms pseudoatvirkštinių matricų normomis.

Tam tikslui generuokite kokius 10000 kartų atsitiktinę  $3 \times 6$ matricą, kurios elementai yra atsitiktiniai skaičiai iš intervalo $[-1,1]$. Po to skaičiuokite jos normą, jai pseudoatvirkštinę ir jos  normą. Galų gale nubraižykite  naudodami matplotlib abiejų matricų normų histogramas. Ar matosi koks nors dėsningumas (priklasomybė) tarp abiejų histogramų?

*Pastaba.* Žr. pvz. https://pythonspot.com/matplotlib-histogram/ , tam, kad prismintume kaip kurti histogramas...